name: CI

on:
  push:
    branches:
      - main  # Run on pushes to the main branch (or whichever branch you prefer)
  pull_request:
    branches:
      - main  # Run on pull requests to the main branch (or whichever branch you prefer)

jobs:
  lint:
    runs-on: ubuntu-latest # You can choose another operating system here
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11" # Specify your Python version here

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Ruff
        run: ruff .

      - name: Check Ruff results
        run: |
          ruff_exit_code=$?
          if [[ $ruff_exit_code -ne 0 ]]; then
            echo "Ruff found errors. Exiting with non-zero code."
            exit $ruff_exit_code
          fi
